"""
Pure sandbox verification — no LLM call anywhere in this file.

Extracted from services.harness_generator's _compiles/_verify (same logic,
same sandbox — services.piston, the Wandbox/Piston backend real candidates'
own submissions run through), but taking already-authored source as input
instead of generating it internally. Used by scripts/repair_question_bank.py
to check content a human (not this codebase's own LLM pipeline) has written
for a (question, language) gap, before anything is persisted to Supabase.

Nothing here ever trusts a claimed-correct value — verify_against_tests
actually compiles and runs the boilerplate (proving the candidate-facing stub
is valid on its own) and separately compiles+runs a reference solution against
the harness, checking that every one of the harness's own reported results is
passed:true.
"""

from __future__ import annotations

import json

from services import piston

_VERSION = {"java": "15.0.2", "cpp": "10.2.0", "node": "18.15.0", "python": "3.10.0"}
_PISTON_LANG = {"java": "java", "cpp": "gcc", "node": "node", "python": "python"}


async def compiles(language: str, source: str) -> tuple[bool, str]:
    """Runs `source` through the sandbox and checks it doesn't blow up.
    Returns (ok, error_detail)."""
    result = await piston.run_code(_PISTON_LANG[language], _VERSION[language], source, stdin="")
    raw = result.get("run", {})
    if raw.get("stderr") and raw.get("code", 0) != 0:
        return False, raw["stderr"][:1500]
    return True, ""


def _parse_result_lines(stdout: str, n_expected: int) -> list[dict] | None:
    results = []
    for line in stdout.strip().splitlines():
        line = line.strip()
        if not line:
            continue
        try:
            results.append(json.loads(line))
        except json.JSONDecodeError:
            continue
    if len(results) != n_expected:
        return None
    return results


async def verify_against_tests(
    language: str, boilerplate: str, harness: str, reference_solution: str, n_tests: int,
    merge_sources,
) -> tuple[bool, str]:
    """boilerplate/harness/reference_solution are author-supplied (by me, per
    question, not LLM-generated by this codebase). merge_sources is
    harness_generator.merge_sources — reused as-is, since the import-order
    fixups it does (hoisting Java imports / C++ includes above the candidate's
    class) apply identically regardless of who wrote the pieces.

    Two-stage check, matching harness_generator._verify exactly:
      1. boilerplate + harness must compile standalone (proves the
         candidate-facing stub, with its placeholder body, is valid on its own).
      2. reference_solution + harness must compile AND RUN, printing exactly
         n_tests JSON result lines, every one of which reports passed:true.
    """
    boilerplate_source = merge_sources(language, [boilerplate, harness])
    ok, err = await compiles(language, boilerplate_source)
    if not ok:
        return False, f"The BOILERPLATE (with its placeholder body) failed to compile:\n{err}"

    full_source = merge_sources(language, [reference_solution, harness])
    result = await piston.run_code(_PISTON_LANG[language], _VERSION[language], full_source, stdin="")
    raw = result.get("run", {})
    if raw.get("stderr") and raw.get("code", 0) != 0:
        return False, f"The REFERENCE SOLUTION + HARNESS failed to compile/run:\n{raw['stderr'][:1500]}"

    results = _parse_result_lines(raw.get("stdout", ""), n_tests)
    if results is None:
        return False, (
            f"Expected exactly {n_tests} JSON result lines (one per test case), got "
            f"{len((raw.get('stdout') or '').strip().splitlines())}. stdout was:\n"
            f"{(raw.get('stdout') or '')[:1500]}"
        )
    if not all(r.get("passed") for r in results):
        return False, (
            "The reference solution (assumed correct) failed some test cases per the harness — "
            "the harness's comparison logic or test-input translation is wrong, not necessarily "
            f"the solution. Results: {json.dumps(results)[:1000]}"
        )
    return True, ""


async def verify_call_expected_case(language: str, reference_solution: str, call: str, expected_check_code: str) -> tuple[bool, str]:
    """For the test-count top-up path: runs a single proposed {call, expected}
    pair against a reference Python solution, to confirm the claimed expected
    value is actually what the code produces — never trusting an authored
    "expected" unchecked. `expected_check_code` is a small script (source +
    call + assert/print) built by the caller; this just executes it and
    reports pass/fail."""
    result = await piston.run_code(_PISTON_LANG[language], _VERSION[language], expected_check_code, stdin="")
    raw = result.get("run", {})
    if raw.get("stderr") and raw.get("code", 0) != 0:
        return False, raw["stderr"][:1500]
    return True, raw.get("stdout", "")
