"""Pilot batch: hand-authored Java/C++/JS boilerplate + reference solutions
for 2 technical questions with zero prior language-generation attempts.

Java/C++ harness DRIVER code is built by the existing deterministic (no-LLM)
template functions in import_neenza_boilerplate.py (build_java_harness/
build_cpp_harness) — I supply the method signature (params/return type, read
by hand off each problem) and my own hand-written reference solution; the
driver that declares test literals and prints the {id,label,...,passed} JSON
schema is generated by that fixed, reviewed template, not invented per
question. Everything is then verified against the REAL sandbox
(services.harness_verify / services.piston) before any persistence."""

import sys, os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
sys.path.insert(0, os.path.dirname(__file__))

from import_neenza_boilerplate import build_java_harness, build_cpp_harness  # noqa: E402

PILOT = {
    "find-indices-of-stable-mountains": dict(
        java=dict(
            params=[(("array", ("prim", "int")), "height"), (("prim", "int"), "threshold")],
            ret_type=("array", ("prim", "int")),
            method_name="stableMountains",
            boilerplate='''class Solution {
    public int[] stableMountains(int[] height, int threshold) {
        return null;
    }
}
''',
            solution='''class Solution {
    public int[] stableMountains(int[] height, int threshold) {
        java.util.List<Integer> res = new java.util.ArrayList<>();
        for (int i = 1; i < height.length; i++) {
            if (height[i - 1] > threshold) res.add(i);
        }
        int[] arr = new int[res.size()];
        for (int i = 0; i < res.size(); i++) arr[i] = res.get(i);
        return arr;
    }
}
''',
        ),
        cpp=dict(
            params=[(("vector", ("prim", "int")), "height"), (("prim", "int"), "threshold")],
            ret_type=("vector", ("prim", "int")),
            method_name="stableMountains",
            boilerplate='''class Solution {
public:
    vector<int> stableMountains(vector<int>& height, int threshold) {
        return {};
    }
};
''',
            solution='''class Solution {
public:
    vector<int> stableMountains(vector<int>& height, int threshold) {
        vector<int> res;
        for (int i = 1; i < (int)height.size(); i++) {
            if (height[i - 1] > threshold) res.push_back(i);
        }
        return res;
    }
};
''',
        ),
        node=dict(
            boilerplate='''class Solution {
    /**
     * @param {number[]} height
     * @param {number} threshold
     * @return {number[]}
     */
    stableMountains(height, threshold) {

    }
}
''',
            solution='''class Solution {
    stableMountains(height, threshold) {
        const res = [];
        for (let i = 1; i < height.length; i++) {
            if (height[i - 1] > threshold) res.push(i);
        }
        return res;
    }
}
''',
        ),
    ),
    "minimum-positive-sum-subarray": dict(
        java=dict(
            params=[(("array", ("prim", "int")), "nums"), (("prim", "int"), "l"), (("prim", "int"), "r")],
            ret_type=("prim", "int"),
            method_name="minimumSumSubarray",
            boilerplate='''class Solution {
    public int minimumSumSubarray(int[] nums, int l, int r) {
        return 0;
    }
}
''',
            solution='''class Solution {
    public int minimumSumSubarray(int[] nums, int l, int r) {
        int n = nums.length;
        Integer best = null;
        for (int i = 0; i < n; i++) {
            long sum = 0;
            for (int j = i; j < n; j++) {
                sum += nums[j];
                int len = j - i + 1;
                if (len >= l && len <= r && sum > 0) {
                    if (best == null || sum < best) best = (int) sum;
                }
            }
        }
        return best == null ? -1 : best;
    }
}
''',
        ),
        cpp=dict(
            params=[(("vector", ("prim", "int")), "nums"), (("prim", "int"), "l"), (("prim", "int"), "r")],
            ret_type=("prim", "int"),
            method_name="minimumSumSubarray",
            boilerplate='''class Solution {
public:
    int minimumSumSubarray(vector<int>& nums, int l, int r) {
        return 0;
    }
};
''',
            solution='''class Solution {
public:
    int minimumSumSubarray(vector<int>& nums, int l, int r) {
        int n = nums.size();
        bool found = false;
        long long best = 0;
        for (int i = 0; i < n; i++) {
            long long sum = 0;
            for (int j = i; j < n; j++) {
                sum += nums[j];
                int len = j - i + 1;
                if (len >= l && len <= r && sum > 0) {
                    if (!found || sum < best) { best = sum; found = true; }
                }
            }
        }
        return found ? (int)best : -1;
    }
};
''',
        ),
        node=dict(
            boilerplate='''class Solution {
    /**
     * @param {number[]} nums
     * @param {number} l
     * @param {number} r
     * @return {number}
     */
    minimumSumSubarray(nums, l, r) {

    }
}
''',
            solution='''class Solution {
    minimumSumSubarray(nums, l, r) {
        const n = nums.length;
        let best = null;
        for (let i = 0; i < n; i++) {
            let sum = 0;
            for (let j = i; j < n; j++) {
                sum += nums[j];
                const len = j - i + 1;
                if (len >= l && len <= r && sum > 0) {
                    if (best === null || sum < best) best = sum;
                }
            }
        }
        return best === null ? -1 : best;
    }
}
''',
        ),
    ),
}
